import { Artifact, ArtifactId } from '@/types/game-types';

export const ARTIFACTS: Record<ArtifactId, Artifact> = {
  seed_spore: {
    id: 'seed_spore',
    name: '생존의 포자',
    description: '섞기 비용을 5회에서 3회로 감소',
    effect: { type: 'cost_reduction', value: 2 },
    isActive: false,
    icon: '🌱',
    color: 'text-green-400',
    rarity: 'common' as const,
  },
  leaf_balance: {
    id: 'leaf_balance',
    name: '균형의 잎맥',
    description: '섞기 비용을 5회에서 2회로 감소',
    effect: { type: 'cost_reduction', value: 3 },
    isActive: false,
    icon: '🍃',
    color: 'text-lime-400',
    rarity: 'rare' as const,
  },
  vine_link: {
    id: 'vine_link',
    name: '연결의 덩굴',
    description: '콤보 시 추가 이동 횟수 +1',
    effect: { type: 'combo_boost', value: 1 },
    isActive: false,
    icon: '🌿',
    color: 'text-yellow-400',
    rarity: 'common' as const,
  },
  blossom_burst: {
    id: 'blossom_burst',
    name: '꽃망울의 폭주',
    description: '콤보 시 추가 이동 횟수 +2',
    effect: { type: 'combo_boost', value: 2 },
    isActive: false,
    icon: '🌸',
    color: 'text-red-400',
    rarity: 'rare' as const,
  },
  stellar_broom: {
    id: 'stellar_broom',
    name: '우주의 빗자루',
    description: '매 5턴마다 가장 높은 등급 타일 1개 자동 제거',
    effect: { type: 'auto_remove', value: 5 },
    isActive: false,
    icon: '🪐',
    color: 'text-purple-400',
    rarity: 'common' as const,
  },
  primal_cleanser: {
    id: 'primal_cleanser',
    name: '태초의 정화자',
    description: '매 3턴마다 가장 높은 등급 타일 1개 자동 제거',
    effect: { type: 'auto_remove', value: 3 },
    isActive: false,
    icon: '🌌',
    color: 'text-pink-400',
    rarity: 'epic' as const,
  },
  starlight_core: {
    id: 'starlight_core',
    name: '별빛 축전기',
    description: '모든 매치 점수 10% 증가',
    effect: { type: 'score_boost', value: 0.1 },
    isActive: false,
    icon: '🔋',
    color: 'text-orange-400',
    rarity: 'common' as const,
  },
  twin_core: {
    id: 'twin_core',
    name: '쌍성 축전기',
    description: '모든 매치 점수 20% 증가',
    effect: { type: 'score_boost', value: 0.2 },
    isActive: false,
    icon: '✨',
    color: 'text-indigo-400',
    rarity: 'rare' as const,
  },
  comet_blessing: {
    id: 'comet_blessing',
    name: '유성의 축복',
    description: '1등급 타일 매치 시 10% 확률로 3등급으로 승급',
    effect: { type: 'special', value: 0.1, condition: 'tier_upgrade' },
    isActive: false,
    icon: '☄️',
    color: 'text-emerald-400',
    rarity: 'epic' as const,
  },
  // 새로운 유물들 - 주요 효과만 선별
  time_warp: {
    id: 'time_warp',
    name: '시간 왜곡기',
    description: '10턴마다 다음 3턴 동안 모든 점수 2배',
    effect: { type: 'turn_based', value: 2, triggerTurn: 10, duration: 3 },
    isActive: false,
    icon: '⏰',
    color: 'text-cyan-400',
    rarity: 'legendary' as const,
  },
  chaos_engine: {
    id: 'chaos_engine',
    name: '카오스 엔진',
    description: '매 3턴마다 랜덤하게 타일 2개 위치 교체',
    effect: { type: 'turn_based', value: 2, triggerTurn: 3, condition: 'random_swap' },
    isActive: false,
    icon: '🌪️',
    color: 'text-purple-500',
    rarity: 'epic' as const,
  },
  crystal_converter: {
    id: 'crystal_converter',
    name: '크리스탈 변환기',
    description: '매 7턴마다 랜덤 타일 3개를 최고 등급으로 변환',
    effect: { type: 'turn_based', value: 3, triggerTurn: 7, condition: 'convert_max_tier' },
    isActive: false,
    icon: '💎',
    color: 'text-pink-400',
    rarity: 'epic' as const,
  },
  mystery_box: {
    id: 'mystery_box',
    name: '미스터리 박스',
    description: '매 5턴마다 랜덤 아이템 1개 획득',
    effect: { type: 'turn_based', value: 1, triggerTurn: 5, condition: 'random_item' },
    isActive: false,
    icon: '📦',
    color: 'text-yellow-600',
    rarity: 'epic' as const,
  },
  bomb_enhancer: {
    id: 'bomb_enhancer',
    name: '폭탄 강화기',
    description: '폭탄 사용 시 5x5 범위로 확장하여 제거',
    effect: { type: 'item_enhancement', value: 1, condition: 'bomb_5x5' },
    isActive: false,
    icon: '💣',
    color: 'text-red-500',
    rarity: 'rare' as const,
  },
};
