import { Artifact, ArtifactId } from '@/types/game-types';

export const ARTIFACTS: Record<ArtifactId, Artifact> = {
  seed_spore: {
    id: 'seed_spore',
    name: '생존의 포자',
    description: '섞기 비용을 5회에서 3회로 감소',
    effect: { type: 'cost_reduction', value: 2 },
    isActive: false,
    icon: '🌱',
    color: 'text-green-400',
  },
  leaf_balance: {
    id: 'leaf_balance',
    name: '균형의 잎맥',
    description: '섞기 비용을 5회에서 2회로 감소',
    effect: { type: 'cost_reduction', value: 3 },
    isActive: false,
    icon: '🍃',
    color: 'text-lime-400',
  },
  vine_link: {
    id: 'vine_link',
    name: '연결의 덩굴',
    description: '콤보 시 추가 이동 횟수 +1',
    effect: { type: 'combo_boost', value: 1 },
    isActive: false,
    icon: '🌿',
    color: 'text-yellow-400',
  },
  blossom_burst: {
    id: 'blossom_burst',
    name: '꽃망울의 폭주',
    description: '콤보 시 추가 이동 횟수 +2',
    effect: { type: 'combo_boost', value: 2 },
    isActive: false,
    icon: '🌸',
    color: 'text-red-400',
  },
  stellar_broom: {
    id: 'stellar_broom',
    name: '우주의 빗자루',
    description: '매 5턴마다 가장 높은 등급 타일 1개 자동 제거',
    effect: { type: 'auto_remove', value: 5 },
    isActive: false,
    icon: '🪐',
    color: 'text-purple-400',
  },
  primal_cleanser: {
    id: 'primal_cleanser',
    name: '태초의 정화자',
    description: '매 3턴마다 가장 높은 등급 타일 1개 자동 제거',
    effect: { type: 'auto_remove', value: 3 },
    isActive: false,
    icon: '🌌',
    color: 'text-pink-400',
  },
  starlight_core: {
    id: 'starlight_core',
    name: '별빛 축전기',
    description: '모든 매치 점수 10% 증가',
    effect: { type: 'score_boost', value: 0.1 },
    isActive: false,
    icon: '🔋',
    color: 'text-orange-400',
  },
  twin_core: {
    id: 'twin_core',
    name: '쌍성 축전기',
    description: '모든 매치 점수 20% 증가',
    effect: { type: 'score_boost', value: 0.2 },
    isActive: false,
    icon: '✨',
    color: 'text-indigo-400',
  },
  comet_blessing: {
    id: 'comet_blessing',
    name: '유성의 축복',
    description: '1등급 타일 매치 시 10% 확률로 3등급으로 승급',
    effect: { type: 'special', value: 0.1, condition: 'tier_upgrade' },
    isActive: false,
    icon: '☄️',
    color: 'text-emerald-400',
  },
};
